name: MM test
favicon: null
layout_spectrum: 0.4954025635961443
typography_spectrum: 0.4673264380544424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3974451886024326
  lightness: 0.37637272430583835
  saturation: 0.30114015634171665
  rhythmicContrast: 0.6936792859341949
purpose: []
