name: MM test
favicon: null
layout_spectrum: 0.24905
typography_spectrum: 0.63619
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#868684'
    - '#d4d8e1'
    - '#f3f8fb'
    - '#412d1f'
    - '#616463'
  brandStrength: 0
  lightness: 0.37637272430583835
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
